default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_POSTGRESQL_POOL') { 5 } %>
  timeout: <%= ENV.fetch('RAILS_POSTGRESQL_TIMEOUT') { 5000 } %>

development:
  <<: *default
  database: agendamento_covid_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: postgres
  port: 5432

test:
  <<: *default
  encoding: utf8
  timeout: 5000
  database: agendamento_covid_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { '' } %>
  host: postgres
  port: 5432

production:
  <<: *default
  host: app-53bae87c-af44-4c3e-b86e-3780a8827f75-do-user-8116555-0.b.db.ondigitalocean.com
  database: db
  username: db
  password: s55cpdvia7nmmr2u
