# be sure to restart your server when you modify this file...
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
development:
  secret_key_base:  pedro

test:
  secret_key_base:  pedro

production:
  secret_key_base: pedro
